// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-THJLpAmkl3c66T3VWzRvjD6DoqHhVKc',
    appId: '1:455927878667:web:4f3974159de3d578bc630e',
    messagingSenderId: '455927878667',
    projectId: 'app-ban-giay-e0124',
    authDomain: 'app-ban-giay-e0124.firebaseapp.com',
    storageBucket: 'app-ban-giay-e0124.firebasestorage.app',
    databaseURL: "https://app-ban-giay-e0124-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1CUxkhfoOWXQq-B3Mc07EyEaoPjYwJog',
    appId: '1:455927878667:android:8be9d66fa47cc1b6bc630e',
    messagingSenderId: '455927878667',
    projectId: 'app-ban-giay-e0124',
    storageBucket: 'app-ban-giay-e0124.firebasestorage.app',
    databaseURL: "https://app-ban-giay-e0124-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoSlzNBu8vr4wBJ4LlLiDyXE6J_eFzi20',
    appId: '1:455927878667:ios:d92484030f3858aabc630e',
    messagingSenderId: '455927878667',
    projectId: 'app-ban-giay-e0124',
    storageBucket: 'app-ban-giay-e0124.firebasestorage.app',
    iosBundleId: 'com.example.appbangiay',
    databaseURL: "https://app-ban-giay-e0124-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoSlzNBu8vr4wBJ4LlLiDyXE6J_eFzi20',
    appId: '1:455927878667:ios:d92484030f3858aabc630e',
    messagingSenderId: '455927878667',
    projectId: 'app-ban-giay-e0124',
    storageBucket: 'app-ban-giay-e0124.firebasestorage.app',
    iosBundleId: 'com.example.appbangiay',
    databaseURL: "https://app-ban-giay-e0124-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-THJLpAmkl3c66T3VWzRvjD6DoqHhVKc',
    appId: '1:455927878667:web:ed4db13e521cd714bc630e',
    messagingSenderId: '455927878667',
    projectId: 'app-ban-giay-e0124',
    authDomain: 'app-ban-giay-e0124.firebaseapp.com',
    storageBucket: 'app-ban-giay-e0124.firebasestorage.app',
    databaseURL: "https://app-ban-giay-e0124-default-rtdb.firebaseio.com",
  );
}
